### ISSUE TITLE
breaks core mod directory

### ISSUE THREAD

**Issue by chuckthebuck** [NuggoDEV/Qolour-Switcher#2]
it for some reason when installed causes BMBF to attempt to redownload coremods and breaks the codegen filepath with it not bing able to find the parsed codegen file (the file is at the right directory.

**Comment by speecil** [comment]
This is usually caused by installing a mod that is for a version different to the version you are currently on. Check that you are on the correct version that it says on the mod post. If you are certain that you are on a version supported by Qolour Switcher please reply with more info as to whats happening, as well as sending screenshots.
